language: java
dist: trusty
sudo: false
install: true
addons:
  sonarcloud:
    organization: alero
    token:
      secure: "S7d6D76GhSm4GRAlGem8Y5kNGNfRIhmq3JfWWaugq5YeNUIUzAih1+O0NIUKiZ2IDURbABlGSD5ex0HtJioWXeI/0m775X3Kbkvd/+jrh4KYw6O6ctngx6/gslBc3HaP9neeaEN28W7S9q8ix16Vk0R/aB9q82PCzwF1uuidOManSqvCQ0L4P6kqjDsscB4fUJDHMfPxm5SPzU1tZescGRyWKPtB9AqbdgEse+mTkQ5NDxn1JJy+sKnk1uoP85JN3RXhVnEuxhknZjv4QscayXXrUrIuck/HUYJN0x8pFldGk1erK4kR7ymJc8PjH+ZTcqdKPfBNuJhTivYkg0G5zcYYj0n+zWwT0N6c5kh9HIwxvZ1aicGAH2US+jSo5zhLWeJ6cBAEG1L9/7kKlJAuGVXMn/DaMR2KcEb8z5LtUmnljWwAaJPgm3L8xTPheD7OvsYua6fPF1IeqSRzwKFIlfC1lZ3fVh2XedALC04MLyR6QEor89xxxnOrCvnHQpzTinBzVnaq56xTFOkrimxJE9WpHnZXLJ3uwsLNV6sEv+7wSbGX7e7YXXsbnSHmHgYT5NNFeI42tCUa+G1XnEmJardK/ABcF3g3P2jOiRuGSLhzOXUKmGMtk1rBbR0ex3vqnTfdi6LxplIQ9j8Hm3AY9t161yEG+T/lNbqThyoN/TM="
jdk:
- oraclejdk8
script:
- mvn -B -q clean clover:setup verify clover:aggregate clover:clover sonar:sonar -Psonar-reporting -Dsonar.projectKey=alero
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
